Move worker script
igorbenav/FastAPI-boilerplate pull request #97
Opened 2024-01-09 01:43 UTC by AlessioBugetti

- created a `worker` folder inside `core` and moved the worker logic to this new folder (`app/worker.py` -> `app/core/worker/settings.py`, `app/core/worker/functions.py`)
- updated the `README.md`

Fix #94

2024-01-09 22:59 UTC, igorbenav requested changes
Don't forget to run before PR, I'm getting:

```sh
fastapi-boilerplate-worker-1  | Traceback (most recent call last):
fastapi-boilerplate-worker-1  |   File "/usr/local/bin/arq", line 8, in <module>
fastapi-boilerplate-worker-1  |     sys.exit(cli())
fastapi-boilerplate-worker-1  |              ^^^^^
fastapi-boilerplate-worker-1  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
fastapi-boilerplate-worker-1  |     return self.main(*args, **kwargs)
fastapi-boilerplate-worker-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
fastapi-boilerplate-worker-1  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
fastapi-boilerplate-worker-1  |     rv = self.invoke(ctx)
fastapi-boilerplate-worker-1  |          ^^^^^^^^^^^^^^^^
fastapi-boilerplate-worker-1  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
fastapi-boilerplate-worker-1  |     return ctx.invoke(self.callback, **ctx.params)
fastapi-boilerplate-worker-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fastapi-boilerplate-worker-1  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
fastapi-boilerplate-worker-1  |     return __callback(*args, **kwargs)
fastapi-boilerplate-worker-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
fastapi-boilerplate-worker-1  |   File "/usr/local/lib/python3.11/site-packages/arq/cli.py", line 40, in cli
fastapi-boilerplate-worker-1  |     worker_settings_ = cast('WorkerSettingsType', import_string(worker_settings))
fastapi-boilerplate-worker-1  |                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fastapi-boilerplate-worker-1  |   File "/usr/local/lib/python3.11/site-packages/arq/utils.py", line 146, in import_string
fastapi-boilerplate-worker-1  |     module = import_module(module_path)
fastapi-boilerplate-worker-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^
fastapi-boilerplate-worker-1  |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
fastapi-boilerplate-worker-1  |     return _bootstrap._gcd_import(name[level:], package, level)
fastapi-boilerplate-worker-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
fastapi-boilerplate-worker-1  |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
fastapi-boilerplate-worker-1  |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
fastapi-boilerplate-worker-1  |   File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
fastapi-boilerplate-worker-1  | ModuleNotFoundError: No module named 'app.worker'
```

You need to update the reference in `docker-compose.yml` as well.

2024-01-10 00:25 UTC, AlessioBugetti commented
I have updated the reference in docker-compose.yml and updated the README.md

2024-01-10 02:09 UTC, igorbenav approved these changes

2024-01-10 02:09 UTC, igorbenav commented
@AlessioBugetti nice one, thanks!

2024-01-10 02:10 UTC, merged